function(load_if_not_exists relpath uri)
    message(STATUS "Check ${relpath}")
    if (EXISTS ${CMAKE_SOURCE_DIR}/${relpath})
        message(STATUS "Already exists")
    else()
        message(STATUS "Download ${relpath}")
        file(DOWNLOAD ${uri} ${CMAKE_SOURCE_DIR}/${relpath})
        message(STATUS "Done")
    endif()
endfunction()

function(CheckAndLoadDependencies)
    load_if_not_exists(3rdparty/json/include/json.hpp https://github.com/nlohmann/json/releases/download/v2.1.1/json.hpp)
endfunction()